Organi/Organi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('changeme', admin.site.urls), # TODO CHANGE the ADMIN PATH for security reasons
    path('', include(('Organiapp.urls', 'Organiapp'), namespace='Organiapp')),
]

Organi/Organiapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
#from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.entryView, name='entry'),
    path('index/', views.indexView, name='index'),
    re_path(r'^index/(?P<list_id>[0-9]+)/$', views.detailView, name='detail'),
]

Organi/Organiapp/models.py
from django.db import models

# Create your models here.

class List(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateField(auto_now=True, auto_now_add=False)
    
    class Meta:
        verbose_name = ("list")
        verbose_name_plural = ("lists")

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateField(auto_now=True, auto_now_add=False)
    list_host = models.ForeignKey(List, on_delete=models.CASCADE)
    date_limit = models.DateField(auto_now=False, auto_now_add=False, default=None, blank=True, null=True)

    class Meta:
        verbose_name = ("item")
        verbose_name_plural = ("items")
    
    def __str__(self):
        return self.name

Organi/Organiapp/forms.py
from django.forms import TextInput, ModelForm, DateField, DateInput, SelectDateWidget
from .models import Item
from django.forms.utils import ErrorList
from django import forms
from django.db import models


class inputItem(ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'date_limit']
        widgets = {
            'name': TextInput(attrs={
                'class': 'search-txt',
                'placeholder': 'Task here ...',
                }),
            'date_limit': SelectDateWidget(attrs={'class': 'date'}),
        }

class ParagraphErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()
    def as_divs(self):
        if not self: return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<p class="small error">%s</p>' % e for e in self])

Organi/Organiapp/views.py
from django.shortcuts import render
from .forms import inputItem, ParagraphErrorList
import datetime

# Create your views here.
from .models import List, Item

def entryView(request):

    context={

    }
    return render(request, 'Organiapp/entry.html', context)


def indexView(request):
    if request.method == 'POST':
        typped = request.POST.get('add_task')
        delete = request.POST.get('delete_task')

        if typped != '':
            new_entry = List(
                name=typped,
            )
            new_entry.save()
        
        if delete != '' and typped == '':
            task = List.objects.filter(id=delete)
            task.delete()

    lists = List.objects.all()
    context = {
        'lists': lists,
    }
    return render(request, 'Organiapp/index.html', context)



def detailView(request, list_id):
    if request.method == 'POST':
        print(request.POST)

        typped = ''
        
        form = inputItem(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            typped = form.cleaned_data['name']
            date = form.cleaned_data['date_limit']
        valid = request.POST.get('valid_task')
        delete = request.POST.get('delete_task')

        if typped != '':
            new_entry = Item(
                name=typped,
                list_host_id=list_id,
                date_limit=date
            )
            new_entry.save()
        
        # valid and delete are the same: it delete the item in database.
        # in next version, a new database takes all the valid entry as archive

        if valid != '' and typped == '':
            task = Item.objects.filter(id=valid)
            task.delete()

        if delete != '' and typped == '':
            task = Item.objects.filter(id=delete)
            task.delete()

    items = Item.objects.filter(list_host_id=list_id).order_by('date_limit')
    listCurrent = List.objects.filter(id=list_id).first()
    form = inputItem()

    urgent_validate = []
    dateCurrent = datetime.date.today()
    for i in range(len(items)):
        if items[i].date_limit is not None:
            if items[i].date_limit < dateCurrent:
                urgent_validate.append(1)
            else:
                urgent_validate.append(0)
        else:
            urgent_validate.append(0)
    
    context = {
        'listCurrent': listCurrent,
        'items': items,
        'form': form,
        'urgent_validate': urgent_validate,
    }
    return render(request, 'Organiapp/detail.html', context)

Organi/Organiapp/templates/Organiapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>OrganiApp</title>
	<link rel="stylesheet" type="text/css" href={% static 'Organiapp/css/style.css' %}>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
{% block content %}
{% endblock content %}
</html>

Organi/Organiapp/templates/Organiapp/detail.html
{% extends 'Organiapp/base.html' %}

{% block content %}
<body>
	<h2>OrganiApp</h2>
	<form action="{% url 'Organiapp:detail' list_id=listCurrent.id %}" method="POST">
    {% csrf_token %}
	<ul>
		<a href={% url 'Organiapp:index' %}><h3 class="listFamily">{{listCurrent.name}}</h3></a>
		{% for item in items %}
		<li>
			<span class="number">{{item.date_limit}}</span>
			<span class="name">{{item.name}}</span>
			<span class="valid_btn"><button type="submit" value="{{item.id}}" name="valid_task"><i id="valid" class="fa fa-check-circle-o" aria-hidden="true"></i></button></span>
			<span class="delete_btn"><button type="submit" value="{{item.id}}" name="delete_task"><i id="delete" class="fa fa-times-circle-o" aria-hidden="true"></i></button></span>
		</li>
		{% endfor %}
	</ul>
	</form>
	<form action="{% url 'Organiapp:detail' list_id=listCurrent.id %}" method="POST">
	{% csrf_token %}
	<h4>{{form.date_limit}}</h4>
	<div class="search-box">
		{{form.name}}
		<input type="submit" class="search-btn" value="GO">
	</div>
	</form>

	<script type="text/javascript">

		var form = document.querySelectorAll('[class="number"]');
		for (var i = 0; i < form.length; i++) {
			if ({{urgent_validate}}[i] == 1){
				form[i].style.backgroundColor = "red"
				form[i].style.borderRadius = "10px"
			}
			if (form[i].innerHTML == "None"){
				form[i].innerHTML = ''
			}
		}
	</script>

</body>
{% endblock content %}

Organi/Organiapp/templates/Organiapp/entry.html
{% extends 'Organiapp/base.html' %}

{% block content %}
<body>
    <h2>OrganiApp</h2>
    <ul>
        <li>
            <a class="listFamily" id="entry-btn" href={% url 'Organiapp:index' %}> <h3>WECLOME</h3> </a>
        </li>
    </ul>
</body>
{% endblock content %}

Organi/Organiapp/templates/Organiapp/index.html
{% extends 'Organiapp/base.html' %}

{% block content %}
<body>
	<h2>OrganiApp</h2>
	<form action="{% url 'Organiapp:index' %}" method="POST">
    {% csrf_token %}
	<ul>
	{% for list in lists %}
		<li>
			<a href={% url 'Organiapp:detail' list_id=list.id %} value="list.id"><h3 class="listFamily" id="listFamily">{{list.name}}</h3></a>
			<span><button type="submit" value="{{list.id}}" name="delete_task"><i id="delete" class="fa fa-times-circle-o" aria-hidden="true"></i></button></span>
		</li>
	{% endfor %}
	</ul>
	<div class="search-box">
		<input class="search-txt" type="text" name="add_task" placeholder="Typ here your new LIST ...">
		
	</div>
	</form>
</body>
{% endblock content %}